name:CI - for application 

on :
  push :
    braches:
      - main
    paths:
      - 'applications/**'

permission:
  contents: write



jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3





